apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-be-nfs-dev
  namespace: dev
spec:
  storageClassName: pv-be-nfs-dev
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: "/home/dev-data-pod/backend/source"
    server: "10.2.2.215"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-be-nfs-dev
  namespace: dev
spec:
  storageClassName: pv-be-nfs-dev
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
